<a href="https://colab.research.google.com/github/Seunsoipe/Python-Synthax-Checkpoint/blob/main/Python_Numpy_Checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Write a Python program to convert an array to an ordinary list with the same items.

In [1]:
from array import *
array_num = array('i', [1, 2, 3, 4, 5, 6, 7, 8])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)


Original array: array('i', [1, 2, 3, 4, 5, 6, 7, 8])
Convert the said array to an ordinary list with the same items:
[1, 2, 3, 4, 5, 6, 7, 8]


Q2. Write a NumPy program to compute the sum of the diagonal element of a given array.

In [4]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)


Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


Q3. Given an array of your choice, get all the values higher than X :if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2.

In [15]:
import numpy as np
x = np.array([[1, 2], [3, 5]])
print("Original array: ")
print(x)
print("Values bigger than 2 =", x[x>2])
print("Their indices are ", np.nonzero(x > 2))



Original array: 
[[1 2]
 [3 5]]
Values bigger than 2 = [3 5]
Their indices are  (array([1, 1]), array([0, 1]))


Q4. Given two arrays A&B having the same shape. The task is to apply addition of A and B : C is the new array.

In [16]:
A = np.array([0, 1, 2])
B = np.array([5, 5, 5])
A + B

array([5, 6, 7])

In [17]:
A = np.array([0, 1, 2])
B = np.array([5, 5, 5])
print("C =", A + B)

C = [5 6 7]
